export const LOCATIONS = [
  'Bariloche',
  'Villa Carlos Paz',
  'Mendoza',
  'San Rafael',
  'Mar del Plata',
  'Salta',
  'Cafayate',
  'Villa Gesell',
  'Puerto Madryn',
  'Ushuaia',
  'San Martin de los Andes',
  'El Calafate',
  'El Bolson',
  'Puerto Iguazu',
  'Tilcara',
  'Pinamar',
  'Miramar',
  'Necochea',
  'Tandil',
  'Villa La Angostura',
  'Las Grutas',
  'Monte Hermoso',
  'San Bernardo',
  'Cordoba',
]
