export const NICHES = [
  'alquiler turistico',
  'cabañas',
  'complejo turistico',
  'hotel boutique',
  'hostel',
  'glamping',
  'posada',
  'resort',
  'departamentos temporarios',
  'alquiler temporario',
  'bungalows',
  'lodge',
  'eco lodge',
  'estancia turistica',
  'hospedaje',
]
